openapi: 3.0.0
info:
  title: openweathermap
  version: '1.0'
  contact:
    name: Support
    url: 'https://openweathermap.org/api'
  termsOfService: 'https://openweathermap.org/terms'
  license:
    name: CC Attribution-ShareAlike 4.0 (CC BY-SA 4.0)
    url: 'https://openweathermap.org/price'
servers:
  - url: 'https://api.openweathermap.org/data/2.5'
paths:
  '/users/{userId}':
    parameters:
      - schema:
          type: integer
        name: userId
        in: path
        required: true
        description: Id of an existing user.
    get:
      summary: Get User Info by User ID
      tags: []
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  coord:
                    type: object
                    required:
                      - lon
                      - lat
                    properties:
                      lon:
                        type: number
                      lat:
                        type: number
                  weather:
                    type: array
                    uniqueItems: true
                    minItems: 1
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                        main:
                          type: string
                          minLength: 1
                        description:
                          type: string
                          minLength: 1
                        icon:
                          type: string
                          minLength: 1
                      required:
                        - id
                        - main
                        - description
                        - icon
                  base:
                    type: string
                    minLength: 1
                  main:
                    type: object
                    required:
                      - temp
                      - feels_like
                      - temp_min
                      - temp_max
                      - pressure
                      - humidity
                    properties:
                      temp:
                        type: number
                      feels_like:
                        type: number
                      temp_min:
                        type: number
                      temp_max:
                        type: number
                      pressure:
                        type: number
                      humidity:
                        type: number
                  visibility:
                    type: number
                  wind:
                    type: object
                    required:
                      - speed
                      - deg
                    properties:
                      speed:
                        type: number
                      deg:
                        type: number
                  clouds:
                    type: object
                    required:
                      - all
                    properties:
                      all:
                        type: number
                  dt:
                    type: number
                  sys:
                    type: object
                    required:
                      - type
                      - id
                      - country
                      - sunrise
                      - sunset
                    properties:
                      type:
                        type: number
                      id:
                        type: number
                      country:
                        type: string
                        minLength: 1
                      sunrise:
                        type: number
                      sunset:
                        type: number
                      '':
                        type: string
                  timezone:
                    type: number
                  id:
                    type: number
                  name:
                    type: string
                    minLength: 1
                  cod:
                    type: number
                  the name:
                    type: string
                required:
                  - coord
                  - weather
                  - base
                  - main
                  - visibility
                  - wind
                  - clouds
                  - dt
                  - sys
                  - timezone
                  - id
                  - name
                  - cod
              examples:
                Get User Alice Smith:
                  value:
                    id: 142
                    firstName: Alice
                    lastName: Smith
                    email: alice.smith@gmail.com
                    dateOfBirth: '1997-10-31'
                    emailVerified: true
                    signUpDate: '2019-08-24'
                example-2:
                  value:
                    coord:
                      lon: -121.95
                      lat: 37.35
                    weather:
                      - id: 803
                        main: Clouds
                        description: broken clouds
                        icon: 04n
                    base: stations
                    main:
                      temp: 45.25
                      feels_like: 41.16
                      temp_min: 41
                      temp_max: 50
                      pressure: 1026
                      humidity: 75
                    visibility: 16093
                    wind:
                      speed: 2.57
                      deg: 36
                    clouds:
                      all: 75
                    dt: 1579415808
                    sys:
                      type: 1
                      id: 5845
                      country: US
                      sunrise: 1579360793
                      sunset: 1579396557
                    timezone: -28800
                    id: 0
                    name: Santa Clara
                    cod: 200
          headers: {}
        '201':
          description: Created
      operationId: get-users-userId
      description: Retrieve the information of the user with the matching user ID.
    patch:
      summary: Update User Information
      operationId: patch-users-userId
      responses:
        '200':
          description: User Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Updated User Rebecca Baker:
                  value:
                    id: 13
                    firstName: Rebecca
                    lastName: Baker
                    email: rebecca@gmail.com
                    dateOfBirth: '1985-10-02'
                    emailVerified: false
                    createDate: '2019-08-24'
        '404':
          description: User Not Found
        '409':
          description: Email Already Taken
      description: Update the infromation of an existing user.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                  description: 'If a new email is given, the user''s email verified property will be set to false.'
                dateOfBirth:
                  type: string
            examples:
              Update First Name:
                value:
                  firstName: Rebecca
              Update Email:
                value:
                  email: rebecca@gmail.com
              Update Last Name & Date of Birth:
                value:
                  lastName: Baker
                  dateOfBirth: '1985-10-02'
        description: Patch user properties to update.
  /user:
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                New User Bob Fellow:
                  value:
                    id: 12
                    firstName: Bob
                    lastName: Fellow
                    email: bob.fellow@gmail.com
                    dateOfBirth: '1996-08-24'
                    emailVerified: false
                    createDate: '2020-11-18'
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                dateOfBirth:
                  type: string
                  format: date
              required:
                - firstName
                - lastName
                - email
                - dateOfBirth
            examples:
              Create User Bob Fellow:
                value:
                  firstName: Bob
                  lastName: Fellow
                  email: bob.fellow@gmail.com
                  dateOfBirth: '1996-08-24'
        description: Post the necessary fields for the API to create a new user.
      description: Create a new user.
  /weather:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
        '201':
          description: Created
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties: {}
            application/xml:
              schema:
                $ref: '#/components/schemas/unauthorized_response'
      operationId: get-weather
      parameters:
        - schema:
            type: string
          in: query
          name: zip
          description: '**zip code **. Search by Zip Code'
        - schema:
            type: string
          in: query
          name: city
          description: '** city *** Search by City'
      description: ''
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      x-examples:
        Alice Smith:
          id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
    unauthorized_response:
      title: unauthorized_response
      type: object
      properties:
        id:
          type: string
  securitySchemes:
    app_id:
      name: API Key
      type: apiKey
      in: query
  responses:
    '200':
      description: Example response
      content:
        application/json:
          schema:
            type: object
            properties:
              id:
                type: string
              '':
                type: string
        application/xml:
          schema:
            type: object
            properties: {}
security: []
